name: Build and Deploy Vue App
on:
  push:
    branches:
      - main  # Změňte na hlavní větev vašeho repozitáře, pokud je jiná

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Změňte na požadovanou verzi Node.js

    - name: Install dependencies
      run: npm install

    - name: Build the Vue app
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
